name: ma6-main-back

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t 2swo/ma6-main-back:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: docker push 2swo/ma6-main-back:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: echo "${{ secrets.SSH_SECRETS_KEY_BASE64 }}" | base64 --decode > $HOME/.ssh/ma6-main-back-key.pem
        env:
          SSH_SECRETS_KEY_BASE64: ${{ secrets.SSH_SECRETS_KEY_BASE64 }}

      - name: Set permissions for SSH key
        run: chmod 600 $HOME/.ssh/ma6-main-back-key.pem

      - name: SSH Connect & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: /github/home/.ssh/ma6-main-back-key.pem
          port: ${{ secrets.PORT }}
          script: |
            docker system prune -a --volumes -f
            docker-compose pull
            docker-compose down
            docker-compose up --force-recreate --build -d --quiet-pull 2> log.out
            cat log.out
